# Generated by Django 2.2.3 on 2020-02-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField(max_length=13)),
                ('Class', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
            ],
        ),
    ]
