# Generated by Django 2.2.3 on 2020-02-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0002_auto_20200229_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('exams_Id', models.IntegerField()),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
