# Generated by Django 2.2.3 on 2020-02-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0003_auto_20200229_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_name', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('exams_Id', models.IntegerField()),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.ImageField(upload_to='')),
                ('Answer', models.CharField(max_length=20)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('exam_question_id', models.IntegerField()),
                ('exams_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Answer_given', models.CharField(max_length=20)),
                ('Correct_Answer', models.IntegerField()),
                ('Score', models.IntegerField()),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
                ('email_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exams.ExamQuestion')),
            ],
        ),
        migrations.DeleteModel(
            name='Exams',
        ),
    ]
