# Generated by Django 2.0.3 on 2020-03-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0004_auto_20200229_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='email_question_id',
            new_name='exam_question_id',
        ),
    ]
